name: realtionshipincomeapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
